### ISSUE TITLE
Slow filtering

### ISSUE THREAD

**Issue by Petermhen** [nk-crew/visual-portfolio#176]
Problem: 
Filtering by categories is abnormally slow. It seems like it refetches all posts every time, even if all posts are loaded already. Thus it's probably the slowest JS based list filtering that I've come across. It's mentioned [here](https://visualportfolio.co/docs/faq/why-the-filtering-takes-time/) 

Feature Request:
I saw from [this source](https://wordpress.org/support/topic/filter-loading-time/) that it should be fixed in the pro version. 

Is it fixed in the Pro version? I've not been able to find any confirmation. If not then I'm requesting it be fixed in Pro. 

The plugin is great & offers a lot for free already so I understand not including this improvement in the free version btw.

If it is fixed then the feature request would be to have this clearly listed as a perk of the Pro version. It would allay user fears that the plugin is just broken in how it handles list filtering. I myself would like confirmation before purchasing the pro version, because the filtering speed is a deal breaker for me unfortunately.

**Comment by nk-o** [comment]
Hey.

Loading is not immediate because of AJAX. Here is an example from our site - https://shot.nkdev.info/B33ZH6GTMd3T56DsvXjK, I don't think it is "abnormally slow" :). It fully depends on your server. If your server is loading the page slowly, the filter will be also slow.

We are using AJAX because the plugin is designed to display dynamic post grids with pagination and other post data. This is by design and not because we don't want it to work faster.

The Pro version adds preloading and caching to AJAX requests, which improves filtering, but not removes the loading time completely. Our site uses the Pro plugin and you can see how the filtering is working here - https://visualportfolio.co/posts/

Regards, nK.
